services:
  choppsoftapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080

  choppsoftdb:
    container_name: choppsoftdb
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=choppsoft
    volumes:
      - choppsoft:/var/lib/postgresql/data
volumes:
  choppsoft:
